### ISSUE TITLE
Throws invalid_grant:  {"error":"invalid_grant"} with oauth2 greater than 0.9.4

### ISSUE THREAD

**Issue by nicoles** [nickelser/omniauth-moves#4]
Something has changed between oauth2 0.9.4 and 1.0.0 such that the moves strategy no longer works.

Fails with:
invalid_grant: 
{"error":"invalid_grant"}

If I rollback to 0.9.4 it works fine again.

**Comment by nickelser** [comment]
@nicoles thank you for your report -- what versions of relevant gems are you using?

**Comment by nicoles** [comment]
My apologies!

oauth2 (0.9.4)
omniauth (1.3.1)
omniauth-moves (0.0.2)

if I move oauth2 forward to 1.0.0 or 1.1.0 I get the invalid grant issue, but moving omniauth around doesn't seem to cause any issues.

**Comment by we5** [comment]
I have the same problem and are already investigating it. For me it happens with the migration of a project to Rails 5 which comes with the newer OAuth2 version (because of the dependency to rack)

**Comment by nickelser** [comment]
Fixed with #5.
